/**
 * IF ANY VALUES ARE BEING CHANGED HERE, REMEMBER TO CHANGE
 * THE CORRESPONDING VALUES IN THE index.scss FILE.
 */
export const APP_CONTAINER_MIN_WIDTH = 375;

export const APP_CONTAINER_MAX_WIDTH = 1344;

export const APP_CONTAINER_TAB_SIZE_WIDTH = 900;
